### ISSUE TITLE
Crash while playing tears of the kingdom

### ISSUE THREAD

**Issue by N2O-yt** [flathub/org.yuzu_emu.yuzu#1146]
### yuzu Version

1496

### Description

I was just playing and the game it freezes and stops (i think that the crash has a relation to the pause menu because it often happens when I pause)

### Reproduction Certainty

Not always, but often

### System Information

```bash session
System:
  Host: ///// Kernel: 5.15.114-2-MANJARO arch: x86_64
    bits: 64 compiler: gcc v: 13.1.1 Desktop: KDE Plasma v: 5.27.5
    Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: M4A79XTD EVO v: Rev X.0X
    serial: <superuser required> BIOS: American Megatrends v: 2102
    date: 06/17/2010
CPU:
  Info: (it is an overclocked AMD phenom 960T) 6-core model: AMD model bits: 64 type: MCP arch: K10 rev: 0 cache:
    L1: 768 KiB L2: 3 MiB L3: 6 MiB
  Speed (MHz): avg: 3599 high: 3600 min/max: N/A cores: 1: 3599 2: 3600
    3: 3600 4: 3600 5: 3600 6: 3600 bogomips: 43221
  Flags: ht lm nx pae sse sse2 sse3 sse4a svm
Graphics:
  Device-1: AMD Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
    vendor: PC Partner / Sapphire driver: amdgpu v: kernel arch: GCN-1
    bus-ID: 01:00.0 temp: 57.0 C
  Display: x11 server: X.Org v: 21.1.8 driver: X: loaded: amdgpu
    unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.4 renderer: AMD Radeon R9 200 / HD 7900
    Series (tahiti LLVM 15.0.7 DRM 3.42 5.15.114-2-MANJARO) direct-render: Yes
Drives:
  Local Storage: total: 1.36 TiB used: 1 TiB (73.5%)
Info:
  Processes: 232 Uptime: 45m Memory: available: 15.62 GiB
  used: 2.14 GiB (13.7%) Init: systemd Compilers: gcc: 13.1.1 clang: 15.0.7
  Packages: 1306 Shell: Zsh v: 5.9 inxi: 3.3.27
```

### Logs and Backtraces

I get this when i try getting the log:
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump', 'yuzu']' returned non-zero exit status 1.

Otherwise the actual yuzu log is empty.

### Remarks

It might happen because of mods , i will be trying to get an actual log and to see the effects of mods on the game

**Comment by carnytom** [comment]
Dump the shader cache.. it worked for me, but I have a big open because every time I get over 25000 shaders, it starts crashing, the more I get the more it crashes

**Comment by N2O-yt** [comment]
I tried dumping the shaders but it did not work, after a lot of testing i came to the conclusion that the crash happens when i open the menu (inventory), i will also attach another log (the one where i dumped the shaders):
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/12093262/yuzu_log.txt)
