### ISSUE TITLE
Yuzu crash only on Flathub

### ISSUE THREAD

**Issue by iWeaker4You** [flathub/org.yuzu_emu.yuzu#335]
Hello guys, I have had this problem of a crash with Yuzu but only the flatpak version, in the last compiled version of Yuzu it works without problems with the same configuration... only in flatpak it has given me this problem in some games, like SSBU. .

I get this message when the crash occurs in the terminal and the image of a visual message.

![imagen](https://user-images.githubusercontent.com/49424816/156029459-f19503b6-5fdc-4464-89ec-322d21a14607.png)
```


/usr/include/c++/11.2.0/span:384: constexpr std::span<_Type, 18446744073709551615> std::span<_Type, _Extent>::subspan(std::span<_Type, _Extent>::size_type, std::span<_Type, _Extent>::size_type) const [with _Type = unsigned char; long unsigned int _Extent = 18446744073709551615; std::span<_Type, _Extent>::size_type = long unsigned int]: Assertion '__offset + __count <= size()' failed.
/app/bin/yuzu-launcher: línea 24:    13 Abortado                prlimit --nofile=8192 yuzu "$@"
```

**Comment by liushuyu** [comment]
> Hello guys, I have had this problem of a crash with Yuzu but only the flatpak version, in the last compiled version of Yuzu it works without problems with the same configuration... only in flatpak it has given me this problem in some games, like SSBU. .
> 
> I get this message when the crash occurs in the terminal and the image of a visual message.
> 
> [...]
> 
> ```
> 
> 
> /usr/include/c++/11.2.0/span:384: constexpr std::span<_Type, 18446744073709551615> std::span<_Type, _Extent>::subspan(std::span<_Type, _Extent>::size_type, std::span<_Type, _Extent>::size_type) const [with _Type = unsigned char; long unsigned int _Extent = 18446744073709551615; std::span<_Type, _Extent>::size_type = long unsigned int]: Assertion '__offset + __count <= size()' failed.
> /app/bin/yuzu-launcher: línea 24:    13 Abortado                prlimit --nofile=8192 yuzu "$@"
> ```

Can you help us locate the cause of the issue by installing `org.yuzu_emu.yuzu.Debug` and `org.kde.Sdk`?

Then run `flatpak run --command=sh --devel org.yuzu_emu.yuzu`.

In the shell, type `gdb yuzu` then <kbd>Enter</kbd>.

In the GDB shell, type <kbd>r</kbd> then <kbd>Enter</kbd>. When the program crashes, in GDB shell, type `bt` then <kbd>Enter</kbd>. Copy the output data and paste them here.

When you finished, just type <kbd>q</kbd> then <kbd>Enter</kbd> to leave GDB.

Also, please attach `inxi -v3` output to this issue. Because we would like to know which distro and which GPU you are using.

**Comment by iWeaker** [comment]
@liushuyu  thanks, here its the output data: 

Before BT command: 
```
/usr/include/c++/11.2.0/span:384: constexpr std::span<_Type, 18446744073709551615> std::span<_Type, _Extent>::subspan(std::span<_Type, _Extent>::size_type, std::span<_Type, _Extent>::size_type) const [with _Type = unsigned char; long unsigned int _Extent = 18446744073709551615; std::span<_Type, _Extent>::size_type = long unsigned int]: Assertion '__offset + __count <= size()' failed.
--Type <RET> for more, q to quit, c to continue without paging--bt

Thread 222 "yuzu:GPU" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb3fff640 (LWP 237)]
0x00007fffee4354bb in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
```
After BT command: 
```
(gdb) bt
#0  0x00007fffee4354bb in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffee41e867 in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555716bf6 in std::__replacement_assert(char const*, int, char const*, char const*)
    (__file=__file@entry=0x55555699149b "/usr/include/c++/11.2.0/span", __line=__line@entry=384, __function=__function@entry=0x555556991cf0 "constexpr std::span<_Type, 18446744073709551615> std::span<_Type, _Extent>::subspan(std::span<_Type, _Extent>::size_type, std::span<_Type, _Extent>::size_type) const [with _Type = unsigned char; long "..., __condition=__condition@entry=0x5555569914b8 "__offset + __count <= size()")
    at /usr/include/c++/11.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:514
#3  0x0000555555bb28af in std::span<unsigned char, 18446744073709551615ul>::subspan(unsigned long, unsigned long) const
    (this=<synthetic pointer>, __offset=16588928, __count=<optimized out>)
    at /usr/include/c++/11.2.0/span:375
#4  std::span<unsigned char, 18446744073709551615ul>::subspan(unsigned long, unsigned long) const
    (__count=<optimized out>, __offset=16588928, this=<synthetic pointer>)
    at /usr/include/c++/11.2.0/span:375
#5  Vulkan::VKBlitScreen::Draw(Tegra::FramebufferConfig const&, VkFramebuffer_T* const&, Layout::FramebufferLayout, VkExtent2D, bool)
    (this=this@entry=0x7f7df5e780d8, framebuffer=..., host_framebuffer=@0x7fffb3ffea38: 0x555558592e88, layout=..., render_area=..., use_accelerated=use_acceler
```

My inxi -v3: 

```
System:
  Host: iweaker4you Kernel: 5.16.11-tkg-pds x86_64 bits: 64 compiler: gcc 
  v: 10.2.1 Desktop: Xfce 4.16.0 Distro: Debian GNU/Linux 11 (bullseye) 
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A 
  serial: <superuser required> 
  Mobo: ASUSTeK model: PRIME B550M-K v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 2407 
  date: 07/13/2021 
CPU:
  Info: Quad Core model: AMD Ryzen 3 3300X bits: 64 type: MT MCP arch: Zen 2 
  rev: 0 L2 cache: 2 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 64000 
  Speed: 3999 MHz min/max: 2200/4000 MHz boost: enabled Core speeds (MHz): 
  1: 3999 2: 4000 3: 4000 4: 4023 5: 4011 6: 4015 7: 4040 8: 3998 
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] vendor: Gigabyte 
  driver: nvidia v: 470.103.01 bus ID: 0a:00.0 
  Display: x11 server: X.Org 1.20.11 driver: loaded: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 
  v: 4.6.0 NVIDIA 470.103.01 direct render: Yes 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASUSTeK PRIME B450M-A driver: r8169 v: kernel port: f000 
  bus ID: 09:00.0 
  IF: enp9s0 state: up speed: 1000 Mbps duplex: full mac: 24:4b:fe:8c:40:5a 
Drives:
  Local Storage: total: 3.66 TiB used: 1.5 TiB (41.0%) 
Info:
  Processes: 293 Uptime: 4h 35m Memory: 15.6 GiB used: 7.32 GiB (46.9%) 
  Init: systemd runlevel: 5 Compilers: gcc: 10.2.1 clang: 11.0.1-2 
  Packages: 2694 Shell: Bash v: 5.1.4 inxi: 3.3.01 
```

**Comment by liushuyu** [comment]
Thank you very much! This is very helpful.

I will forward your report to our resident GPU expert.

**Comment by iSeth500** [comment]
I have this bug too.

System:
  Host: Comp Kernel: 5.4.0-100-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Xfce 4.16.0 Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop System: Gigabyte product: B450 I AORUS PRO WIFI v: N/A 
  serial: <superuser/root required> 
  Mobo: Gigabyte model: B450 I AORUS PRO WIFI-CF v: x.x 
  serial: <superuser/root required> UEFI [Legacy]: American Megatrends v: F3 
  date: 12/24/2018 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 2600 bits: 64 type: MT MCP arch: Zen+ rev: 2 
  L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 95807 
  Speed: 1374 MHz min/max: 1550/4000 MHz Core speeds (MHz): 1: 1374 2: 1375 3: 1375 
  4: 1375 5: 1375 6: 1374 7: 1375 8: 1374 9: 1375 10: 1374 11: 1375 12: 1374 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] vendor: Gigabyte driver: nvidia 
  v: 510.47.03 bus ID: 09:00.0 
  Display: x11 server: X.Org 1.20.13 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa tty: N/A 
  OpenGL: renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 510.47.03 
  direct render: Yes 
Network:
  Device-1: Intel Wireless-AC 9260 driver: iwlwifi v: kernel bus ID: 06:00.0 
  IF: wlp6s0 state: up mac: 18:1d:ea:f0:f4:01 
  Device-2: Intel I211 Gigabit Network vendor: Gigabyte driver: igb v: 5.6.0-k 
  port: f000 bus ID: 08:00.0 
  IF: enp8s0 state: up speed: 10 Mbps duplex: full mac: b4:2e:99:30:7d:54 
Drives:
  Local Storage: total: 1.13 TiB used: 478.92 GiB (41.5%) 
Info:
  Processes: 357 Uptime: 4d 18h 23m Memory: 7.78 GiB used: 3.60 GiB (46.2%) 
  Init: systemd runlevel: 5 Compilers: gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38

**Comment by liushuyu** [comment]
I think this issue has been fixed by now. Can you help us confirm it by updating to the latest version of yuzu (1253 as of writing)?

**Comment by ultra-azu** [comment]
From my side I still have it.

**Comment by liushuyu** [comment]
> From my side I still have it. Version 1278

Please open a new issue and attach your details, since your crash may have a different cause.

**Comment by liushuyu** [comment]
We have updated the Flatpak runtime in yuzu 1266. Please update to any version newer than 1266 and see if your issue has been fixed.

If not, please open a new issue instead of posting on this thread to avoid clogging the page and obscuring the context.
